import type { GameTemplate, PlayerName, SoulLink } from "@/lib/types";

export const defaultPlayerNames: PlayerName[] = ["Nayan", "Shivank", "Srikar"];
export const defaultGameId = "pokemon-black";

const kantoOriginalAreas = [
  "Starter",
  "Route 1",
  "Route 2",
  "Viridian Forest",
  "Route 3",
  "Mt. Moon",
  "Route 4",
  "Route 24",
  "Route 25",
  "Route 5",
  "Route 6",
  "Route 11",
  "Diglett's Cave",
  "Route 9",
  "Route 10",
  "Rock Tunnel",
  "Route 7",
  "Route 8",
  "Pokemon Tower",
  "Route 12",
  "Route 13",
  "Route 14",
  "Route 15",
  "Route 16",
  "Route 17",
  "Route 18",
  "Safari Zone",
  "Route 19",
  "Route 20",
  "Seafoam Islands",
  "Route 21",
  "Pokemon Mansion",
  "Power Plant",
  "Route 22",
  "Victory Road",
  "Cerulean Cave"
];

const johtoAreas = [
  "Starter",
  "Route 29",
  "Route 46",
  "Route 30",
  "Route 31",
  "Dark Cave",
  "Sprout Tower",
  "Route 32",
  "Ruins of Alph",
  "Union Cave",
  "Route 33",
  "Slowpoke Well",
  "Ilex Forest",
  "Route 34",
  "Route 35",
  "National Park",
  "Route 36",
  "Route 37",
  "Burned Tower",
  "Route 38",
  "Route 39",
  "Route 40",
  "Route 41",
  "Whirl Islands",
  "Mt. Mortar",
  "Route 42",
  "Route 43",
  "Lake of Rage",
  "Route 44",
  "Ice Path",
  "Route 45",
  "Tohjo Falls",
  "Victory Road",
  "Mt. Silver"
];

const hoennAreas = [
  "Starter",
  "Route 101",
  "Route 103",
  "Route 102",
  "Route 104",
  "Petalburg Woods",
  "Route 116",
  "Rusturf Tunnel",
  "Dewford Town",
  "Route 106",
  "Granite Cave",
  "Route 109",
  "Route 110",
  "Route 117",
  "Route 111",
  "Fiery Path",
  "Route 112",
  "Jagged Pass",
  "Route 113",
  "Route 114",
  "Meteor Falls",
  "Route 115",
  "Route 118",
  "Route 119",
  "Route 120",
  "Safari Zone",
  "Route 121",
  "Mt. Pyre",
  "Route 122",
  "Route 123",
  "Route 124",
  "Route 125",
  "Shoal Cave",
  "Route 126",
  "Route 127",
  "Route 128",
  "Seafloor Cavern",
  "Route 129",
  "Route 130",
  "Route 131",
  "Sky Pillar",
  "Route 132",
  "Route 133",
  "Route 134",
  "Victory Road"
];

const kantoRemakeAreas = [
  ...kantoOriginalAreas,
  "One Island",
  "Kindle Road",
  "Mt. Ember",
  "Treasure Beach",
  "Cape Brink",
  "Bond Bridge",
  "Berry Forest",
  "Three Isle Path",
  "Four Island",
  "Icefall Cave",
  "Five Island Meadow",
  "Resort Gorgeous",
  "Water Labyrinth",
  "Lost Cave",
  "Water Path",
  "Ruin Valley",
  "Pattern Bush",
  "Altering Cave",
  "Canyon Entrance",
  "Sevault Canyon",
  "Tanoby Ruins"
];

const sinnohAreas = [
  "Starter",
  "Lake Verity",
  "Route 201",
  "Route 202",
  "Route 203",
  "Oreburgh Gate",
  "Oreburgh Mine",
  "Route 204",
  "Ravaged Path",
  "Valley Windworks",
  "Route 205",
  "Eterna Forest",
  "Old Chateau",
  "Route 206",
  "Wayward Cave",
  "Route 207",
  "Mt. Coronet",
  "Route 208",
  "Route 209",
  "Lost Tower",
  "Solaceon Ruins",
  "Route 210",
  "Route 215",
  "Route 214",
  "Valor Lakefront",
  "Route 213",
  "Great Marsh",
  "Route 212",
  "Trophy Garden",
  "Route 218",
  "Fuego Ironworks",
  "Iron Island",
  "Route 219",
  "Route 220",
  "Route 221",
  "Lake Valor",
  "Route 216",
  "Route 217",
  "Acuity Lakefront",
  "Lake Acuity",
  "Route 222",
  "Victory Road",
  "Route 224",
  "Route 225",
  "Route 226",
  "Route 227",
  "Stark Mountain",
  "Route 228",
  "Route 229",
  "Route 230",
  "Sendoff Spring",
  "Turnback Cave"
];

const johtoRemakeAreas = [
  ...johtoAreas,
  "Cliff Cave",
  "Safari Zone Gate",
  "Safari Zone",
  "Embedded Tower",
  "Route 47",
  "Route 48"
];

export const unovaBlackWhiteAreas = [
  "Starter",
  "Route 1",
  "Route 2",
  "Dreamyard Static",
  "Dreamyard Grass",
  "Wellspring Cave",
  "Route 3",
  "Pinwheel Forest Outside",
  "Pinwheel Forest Inside",
  "Striaton",
  "Castelia",
  "Route 4",
  "Desert Resort",
  "Relic Castle",
  "Route 5",
  "Driftveil Drawbridge",
  "Cold Storage",
  "Route 6",
  "Chargestone Cave",
  "Route 7",
  "Celestial Tower",
  "Mistralton Cave",
  "Guidance Chamber",
  "Twist Mountain",
  "Icirrus City",
  "Dragonspiral Tower",
  "Moor of Icirrus",
  "Route 8",
  "Tubeline Bridge",
  "Route 9",
  "Route 10",
  "Victory Road",
  "Trial Chamber",
  "Route 11",
  "Village Bridge",
  "Route 12",
  "Route 13",
  "Giant Chasm",
  "Route 14",
  "Abundant Shrine",
  "Route 15",
  "Marvelous Bridge",
  "Route 16",
  "Lostlorn Forest",
  "Route 17",
  "Route 18",
  "P2 Laboratory",
  "Undella Town",
  "Undella Bay",
  "Challenger's Cave"
];

const unovaBlackWhiteTwoAreas = [
  "Starter",
  "Route 19",
  "Route 20",
  "Floccesy Ranch",
  "Virbank Complex",
  "Castelia Sewers",
  "Relic Passage",
  "Route 4",
  "Desert Resort",
  "Relic Castle",
  "Route 16",
  "Lostlorn Forest",
  "Route 5",
  "Driftveil Drawbridge",
  "Route 6",
  "Mistralton Cave",
  "Chargestone Cave",
  "Route 7",
  "Celestial Tower",
  "Reversal Mountain",
  "Strange House",
  "Route 13",
  "Undella Town",
  "Undella Bay",
  "Seaside Cave",
  "Route 22",
  "Giant Chasm",
  "Route 23",
  "Victory Road",
  "Route 11",
  "Village Bridge",
  "Route 12",
  "Route 9",
  "Route 21",
  "Route 14",
  "Abundant Shrine",
  "Route 15",
  "Marvelous Bridge",
  "Route 1",
  "Route 2",
  "Route 3",
  "Wellspring Cave",
  "Pinwheel Forest",
  "Dreamyard",
  "Route 18",
  "P2 Laboratory",
  "Clay Tunnel",
  "Twist Mountain",
  "Dragonspiral Tower",
  "Moor of Icirrus",
  "Nature Preserve"
];

export const gameTemplates: GameTemplate[] = [
  {
    id: "pokemon-red-blue-yellow",
    name: "Pokemon Red / Blue / Yellow",
    generation: 1,
    region: "Kanto",
    maxPokemonId: 151,
    usesFairyType: false,
    encounterAreas: kantoOriginalAreas
  },
  {
    id: "pokemon-gold-silver-crystal",
    name: "Pokemon Gold / Silver / Crystal",
    generation: 2,
    region: "Johto",
    maxPokemonId: 251,
    usesFairyType: false,
    encounterAreas: johtoAreas
  },
  {
    id: "pokemon-ruby-sapphire-emerald",
    name: "Pokemon Ruby / Sapphire / Emerald",
    generation: 3,
    region: "Hoenn",
    maxPokemonId: 386,
    usesFairyType: false,
    encounterAreas: hoennAreas
  },
  {
    id: "pokemon-firered-leafgreen",
    name: "Pokemon FireRed / LeafGreen",
    generation: 3,
    region: "Kanto",
    maxPokemonId: 386,
    usesFairyType: false,
    encounterAreas: kantoRemakeAreas
  },
  {
    id: "pokemon-diamond-pearl-platinum",
    name: "Pokemon Diamond / Pearl / Platinum",
    generation: 4,
    region: "Sinnoh",
    maxPokemonId: 493,
    usesFairyType: false,
    encounterAreas: sinnohAreas
  },
  {
    id: "pokemon-heartgold-soulsilver",
    name: "Pokemon HeartGold / SoulSilver",
    generation: 4,
    region: "Johto",
    maxPokemonId: 493,
    usesFairyType: false,
    encounterAreas: johtoRemakeAreas
  },
  {
    id: defaultGameId,
    name: "Pokemon Black / White",
    generation: 5,
    region: "Unova",
    maxPokemonId: 649,
    usesFairyType: false,
    encounterAreas: unovaBlackWhiteAreas
  },
  {
    id: "pokemon-black-2-white-2",
    name: "Pokemon Black 2 / White 2",
    generation: 5,
    region: "Unova",
    maxPokemonId: 649,
    usesFairyType: false,
    encounterAreas: unovaBlackWhiteTwoAreas
  }
];

export function getGameTemplate(gameId: string) {
  return gameTemplates.find((template) => template.id === gameId) ?? gameTemplates.find((template) => template.id === defaultGameId)!;
}

export function createEmptyMembers(playerNames: PlayerName[]): SoulLink["members"] {
  return playerNames.reduce(
    (members, player) => ({
      ...members,
      [player]: null
    }),
    {} as SoulLink["members"]
  );
}

export function createEncounterTemplateLinks(
  gameId = defaultGameId,
  playerNames = defaultPlayerNames
): SoulLink[] {
  const template = getGameTemplate(gameId);

  return template.encounterAreas.map((area, index) => ({
    id: `template-link-${index + 1}`,
    linkNumber: index + 1,
    area,
    status: "Pending",
    members: createEmptyMembers(playerNames)
  }));
}
